In [1]:
import numpy

In [2]:
vector = [1, 2, 3]

In [3]:
print(type(vector))

<class 'list'>


In [4]:
nvector = numpy.array(vector)

In [5]:
nvector.shape

(3,)

In [6]:
matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

In [7]:
nmatrix = numpy.array(matrix)

In [8]:
nmatrix.shape

(3, 3)

In [9]:
j = 3
i = [1, 2, 3]
k = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
x = [
    [[1, 2, 3], [6, 2, 3], [8, 4, 2]],
    [[5, 2, 3], [6, 2, 3], [8, 4, 2]],
    [[1, 7, 3], [6, 2, 3], [8, 4, 2]],
]

In [10]:
narr = numpy.array([1, 2, 3])
narr

array([1, 2, 3])

In [11]:
numpy.resize(narr, (4, 4))

array([[1, 2, 3, 1],
       [2, 3, 1, 2],
       [3, 1, 2, 3],
       [1, 2, 3, 1]])

In [12]:
narr.resize((3, 3), refcheck=False)

In [13]:
narr

array([[1, 2, 3],
       [0, 0, 0],
       [0, 0, 0]])

In [31]:
matrix = numpy.ones((5, 4))

In [15]:
matrix

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
matrix = numpy.zeros((4, 4))
matrix

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
numpy.diag(narr)

array([1, 0, 0])

In [18]:
numpy.repeat([4, 3, 2], 5)

array([4, 4, 4, 4, 4, 3, 3, 3, 3, 3, 2, 2, 2, 2, 2])

In [35]:
m1 = numpy.ones((4, 3), int)
m1

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [20]:
m2 = numpy.zeros((4, 3), int)
m2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [36]:
numpy.vstack([m1, m2])

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [22]:
numpy.hstack([m1, m2])

array([[1, 1, 1, 1, 1, 0, 0, 0],
       [1, 1, 1, 1, 1, 0, 0, 0],
       [1, 1, 1, 1, 1, 0, 0, 0],
       [1, 1, 1, 1, 1, 0, 0, 0]])

In [23]:
x = numpy.array([1, 2, 3])
y = numpy.array([4, 5, 5])


In [24]:
z = x * y
z

array([ 4, 10, 15])

In [25]:
x ** 2

array([1, 4, 9])

In [26]:
x.dot(y)

29

In [27]:
narr

array([[1, 2, 3],
       [0, 0, 0],
       [0, 0, 0]])

In [28]:
narr.T

array([[1, 0, 0],
       [2, 0, 0],
       [3, 0, 0]])

In [29]:
narr.astype('f')

array([[1., 2., 3.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

In [30]:
narr.sum()

6

In [89]:
narr.max()

3

In [90]:
narr.min()

0

In [91]:
narr.argmax()

2

In [92]:
narr.argmin()

3

In [93]:
narr.mean()

0.6666666666666666

In [95]:
narr.std()

1.0540925533894598

In [100]:
mr = numpy.arange(15) ** 2
mr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196])

In [101]:
mr[2]

4

In [102]:
mr[1:5]

array([ 1,  4,  9, 16])

In [106]:
mr[:5]

array([ 0,  1,  4,  9, 16])

In [107]:
mr[-2:]

array([169, 196])

In [110]:
mr[10::-2]

array([100,  64,  36,  16])

In [111]:
narr

array([[1, 2, 3],
       [0, 0, 0],
       [0, 0, 0]])

In [115]:
narr[0:2, 1:3]

array([[2, 3],
       [0, 0]])

In [117]:
narr[::2, -1]

array([3, 0])

In [37]:
narr[narr >= 3]

array([3])

In [119]:
narr >= 2

array([[False,  True,  True],
       [False, False, False],
       [False, False, False]])

In [120]:
marr = narr[-1]
marr

array([0, 0, 0])

In [123]:
marr[:] = 1
marr

array([1, 1, 1])

In [124]:
marr[:2] = 2
marr

array([2, 2, 1])

In [125]:
narr

array([[1, 2, 3],
       [0, 0, 0],
       [2, 2, 1]])

In [127]:
marr = narr.copy()
marr

array([[1, 2, 3],
       [0, 0, 0],
       [2, 2, 1]])

In [129]:
marr[:] = 0
marr

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [130]:
narr

array([[1, 2, 3],
       [0, 0, 0],
       [2, 2, 1]])

In [38]:
tarr = numpy.random.randint(1, 20, (10,12))
tarr

array([[15,  5,  2, 12, 12, 19, 17, 19, 18,  3,  4, 19],
       [ 8, 13, 17, 10, 17,  2, 17, 16,  8, 17,  5, 19],
       [ 6, 14, 18,  4, 16, 11, 19,  9, 16,  3,  8,  5],
       [14, 13, 18, 12,  9, 11,  7,  1,  3,  3,  4, 10],
       [16, 12, 11, 16,  4, 15, 16,  8,  7,  4,  8, 14],
       [ 4,  9, 19,  7,  6,  5,  3,  8, 19, 19, 10,  4],
       [19, 11,  4, 17,  5,  9, 16,  7, 16, 19,  9, 15],
       [18,  3, 19, 19,  7,  4, 13,  3,  1, 13,  1, 10],
       [ 7,  6,  4,  9,  8,  8,  2,  7,  1, 14,  7, 16],
       [13, 12,  4, 11,  2, 12, 19,  8,  6,  2, 10, 12]])

In [42]:
for r in tarr:
    r**=2
    print(r)

[ 900  100   16  576  576 1444 1156 1444 1296   36   64 1444]
[ 256  676 1156  400 1156   16 1156 1024  256 1156  100 1444]
[ 144  784 1296   64 1024  484 1444  324 1024   36  256  100]
[ 784  676 1296  576  324  484  196    4   36   36   64  400]
[1024  576  484 1024   64  900 1024  256  196   64  256  784]
[  64  324 1444  196  144  100   36  256 1444 1444  400   64]
[1444  484   64 1156  100  324 1024  196 1024 1444  324  900]
[1296   36 1444 1444  196   64  676   36    4  676    4  400]
[ 196  144   64  324  256  256   16  196    4  784  196 1024]
[ 676  576   64  484   16  576 1444  256  144   16  400  576]


In [40]:
for i, r in enumerate(tarr):
    print('index(' + str(i) + ') is ', r)

index(0) is  [15  5  2 12 12 19 17 19 18  3  4 19]
index(1) is  [ 8 13 17 10 17  2 17 16  8 17  5 19]
index(2) is  [ 6 14 18  4 16 11 19  9 16  3  8  5]
index(3) is  [14 13 18 12  9 11  7  1  3  3  4 10]
index(4) is  [16 12 11 16  4 15 16  8  7  4  8 14]
index(5) is  [ 4  9 19  7  6  5  3  8 19 19 10  4]
index(6) is  [19 11  4 17  5  9 16  7 16 19  9 15]
index(7) is  [18  3 19 19  7  4 13  3  1 13  1 10]
index(8) is  [ 7  6  4  9  8  8  2  7  1 14  7 16]
index(9) is  [13 12  4 11  2 12 19  8  6  2 10 12]


In [138]:
narr

array([[1, 2, 3],
       [0, 0, 0],
       [2, 2, 1]])

In [139]:
marr

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [141]:
list(zip(narr, marr))

[(array([1, 2, 3]), array([0, 0, 0])),
 (array([0, 0, 0]), array([0, 0, 0])),
 (array([2, 2, 1]), array([0, 0, 0]))]

In [142]:
arr = [1, 4, 2, 9, 8, 6, 3]
arr = numpy.array(arr)
arr

array([1, 4, 2, 9, 8, 6, 3])

In [143]:
len(arr) // 2

3

In [144]:
p = arr[len(arr) // 2]
p

9

In [145]:
l = [x for x in arr if x  < p]
l

[1, 4, 2, 8, 6, 3]

In [146]:
r = [x for x in arr if x > p]
r

[]

In [147]:
m = [x for x in arr if x == p]
m

[9]

In [148]:
l + m + r

[1, 4, 2, 8, 6, 3, 9]

In [149]:
def quicksort(arr):
    if len(arr) <= 1:
        return arr
    arr = numpy.array(arr)
    p = arr[len(arr) // 2]
    l = [x for x in arr if x  < p]
    m = [x for x in arr if x == p]
    r = [x for x in arr if x > p]
    return quicksort(l) + m + quicksort(r)

In [150]:
h = [3, 6, 4, 1, 3, 9, 4]
quicksort(h)

[1, 3, 3, 4, 4, 6, 9]